//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars_Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Trades = new HashSet<Trades>();
        }
    
        public string Госномер { get; set; }
        public string Модель { get; set; }
        public byte ID_типа_кузова { get; set; }
        public byte ID_типа_коробки { get; set; }
        public byte ID_типа_привода { get; set; }
        public byte Объем_двигателя { get; set; }
        public double Расход_на_100_км { get; set; }
        public byte ID_состояния_авто { get; set; }
        public short Год_выпуска { get; set; }
        public byte Количество_мест { get; set; }
        public short Вместимость_багажника { get; set; }
        public byte ID_типа_топлива { get; set; }
        public byte ID_типа_страховки { get; set; }
        public short Цена_за_сутки { get; set; }
        public byte ID_типа_двигателя { get; set; }
        public byte ID_класса_автомобиля { get; set; }
    
        public virtual ID_класса_автомобиля ID_класса_автомобиля1 { get; set; }
        public virtual ID_состояния_авто ID_состояния_авто1 { get; set; }
        public virtual ID_типа_двигателя ID_типа_двигателя1 { get; set; }
        public virtual ID_типа_коробки ID_типа_коробки1 { get; set; }
        public virtual ID_типа_кузова ID_типа_кузова1 { get; set; }
        public virtual ID_типа_привода ID_типа_привода1 { get; set; }
        public virtual ID_типа_страховки ID_типа_страховки1 { get; set; }
        public virtual ID_типа_топлива ID_типа_топлива1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trades> Trades { get; set; }
    }
}
