//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars_Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trades
    {
        public string Номер_сделки { get; set; }
        public string Госномер { get; set; }
        public string Номер_и_серия_паспорта { get; set; }
        public byte ID_статуса_сделки { get; set; }
        public byte Срок_сделки { get; set; }
        public int Сумма_сделки { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ID_статуса_сделки ID_статуса_сделки1 { get; set; }
    }
}
